name: Run test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -e .
        python -m pip install keyrings.alt
    - name: Insert API key
      run: "echo ${{ secrets.API_KEY }} | keyring set rescale default"
    - name: Run test
      run: python tests/list_jobs.py